AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - 'db/**/*'
    - "tmp/**/*"
    - "vendor/**/*"
    - "log/**/*"
    - "node_modules/**/*"

# Rails specific.
Rails:
  Enabled: true

# Project rules.
Style/DoubleNegation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 160 # default was 80.
Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'config/**/*'
    - 'spec/factories/*'
