common: &common
  adapter: postgresql
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  reconnect: true

development:
  <<: *common
  database: <%= ENV['DATABASE_NAME'] %>

test:
  <<: *common
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
